name: bart
checkpoint_name: facebook/bart-base
batch_size: 4
val_batch_size: 16
generate_batch_size: 32
learning_rate: 1e-5
padding_side: right
warmup_fraction: 0.1
checkpoint_dir: checkpoints/bart
cls_loss: kldiv

classification_pos_freq:
  - 0.485 # offensive
  - 0.515 # intentional
  - 0.085 # sex
  - 0.656 # vs_group
  - 0.023 # in_group

classification_thresholds:
  - 0.56
  - 0.43
  - 0.49
  - 0.59
  - 0.39

generation_params:
  num_beams: 1
  early_stopping: False
  do_sample: False  
  max_new_tokens: 100
