name: bart
checkpoint_name: facebook/bart-base
batch_size: 4
val_batch_size: 16
learning_rate: 1e-5
padding_side: right
warmup_fraction: 0.2
checkpoint_dir: checkpoints/bart

cls_weight: 1.0

classification_pos_freq:
  - 0.485 # offensive
  - 0.515 # intentional
  - 0.085 # sex
  - 0.656 # vs_group
  - 0.023 # in_group

generation_parameters:
  penalty_alpha: 0.4
  top_k: 4