name: bart
checkpoint_name: facebook/bart-base
batch_size: 8
learning_rate: 1e-5
padding_side: right
decoder_max_length: 512
warmup_fraction: 0.1
checkpoint_dir: checkpoints/gpt2

generation_parameters:
  penalty_alpha: 0.4
  top_k: 4