data:
  raw:
    train: data/raw/SBIC.v2.trn.csv
    val: data/raw/SBIC.v2.dev.csv
    test: data/raw/SBIC.v2.tst.csv

  clean: data/clean  
  processed: data/processed
  aggregated: data/aggregated
  train:
    gpt2: data/train/gpt2
    bart: data/train/bart

  prediction: prediction

wandb:
  project: social_bias_framework
  entity: group_nlp2022

model:
  num_epochs: 3
  batch_size: 2
  val_batch_size: 64
  generate_batch_size: 32
  num_workers: 2
  learning_rate: 1e-5
  optimizer_name: AdamW
  scheduler: linear
  warmup_fraction: 0.1
  accumulation_steps: 1
  gradient_clip: 1.0
  mixed_precision: fp16
  checkpoint_interval: 700
  log_interval: 700
  device: cuda:0

embedding_model: WhereIsAI/UAE-Large-V1
group_lbl_processor: group-label-processor.pkl
# embedding_model: sentence-transformers/all-mpnet-base-v2